# 1. Image Node officielle
FROM node:20

# 2. Dossier de travail
WORKDIR /app

# 3. Copier package.json + package-lock.json
COPY package*.json ./

# 4. Installer les dépendances
RUN npm install

# 5. Copier le reste du code
COPY . .

# 6. Exposer le port Vite
EXPOSE 5173

# 7. Commande par défaut
CMD ["npm", "run", "dev"]
