# 1. Image Node officielle
FROM node:20

# 2. Créer le dossier de travail
WORKDIR /app

# 3. Copier package.json + package-lock.json
COPY package*.json ./

# 4. Installer les dépendances
RUN npm install

# 5. Copier tout le reste du code
COPY . .

# 6. Exposer le port
EXPOSE 3000

# 7. Commande par défaut
CMD ["npm", "run", "dev"]
